# Generated by Django 5.2 on 2025-04-26 13:54

import todo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=todo_app.models.user_directory_path),
        ),
    ]
